name: Notify

on:
  workflow_run:
    workflows: ["C++ CI Build & Check"] # 对应上面的 job 名
    types:
      - completed

jobs:
  send-notification:
    name: Send Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 这里写你的通知逻辑（如发送到 Slack/企业微信/钉钉等）
      - name: Print Status
        run: |
          echo "Build Status: ${{ github.event.workflow_run.conclusion }}"
